### ISSUE TITLE
Bare line feed characters

### ISSUE THREAD

**Issue by sirowood** [EC-Nordbund/denomailer#11] opened 2022-04-13 06:20 UTC
**Describe the bug**
Your message contains invalid characters (bare line feed characters) which the email servers at yahoo.com don't support.

**To Reproduce**
When sending emails to @yahoo.com with **html**, and **content** property set to 'auto'

**Expected behavior**
No errors.

**Comment by mathe42** [comment] 2022-04-13 06:49
Will look into it. I think there is a quick fix...

**Comment by mathe42** [comment] 2022-04-13 08:58
Coud you provide a html example. I can't reproduce the error...

**Comment by mathe42** [comment] 2022-04-21 12:47
Close this as no reproduction was provided. Feel free to repopen or create a new issue

**Closed by mathe42** 2022-04-21 12:47 UTC
Labels: bug, needs repoduction

**Comment by mathe42** [comment] 2022-04-22 14:00
Maybe fixed by 8e0de37964518e18aa50edb06b99547638ddc3a6
